###
POST http://localhost:8081/add
Content-Type: application/json

{
  "email": "aa@temp.com",
  "firstName": "alexandr",
  "lastName": "alexandrov",
  "age": 20
}

###
GET http://localhost:8081/all

###
GET http://localhost:8081/native/all

###
GET http://localhost:8081/byAge/18

###
GET http://localhost:8081/native/byAge/18


###